heat_template_version: 2018-08-31

description: |
  The heat template is used to demo an autoscaling group.
parameters:
  webserver_key_name: # No default, this a required parameter
    type: string
  webserver_image:
    description: Glance image name or UUID
    type: string
    default: ubuntu-22.04-x86_64
  webserver_flavor:
    type: string
    default: c1.c1r1
  webserver_network:
    type: string
    default: network1
  webserver_public_network:
    description: Public network name, can obtain with 'openstack network list --external'
    type: string
    default: public-net

resources:
  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules: [
        {protocol: "tcp", "port_range_min": 80, "port_range_max": 80},
        {protocol: "tcp", "port_range_min": 22, "port_range_max": 22},
      ]
  autoscaling_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 5
      desired_capacity: 2
      rolling_updates:
        min_in_service: 2 # The minimum number of resources in service while rolling updates are being executed.
        max_batch_size: 1 # The maximum number of resources to replace at once.
        #pause_time: 0  # The number of seconds to wait between batches of updates.
      resource:
        type: webserver.yaml
        properties:
          key_name: {get_param: webserver_key_name}
          flavor: {get_param: webserver_flavor}
          image: {get_param: webserver_image}
          network: {get_param: webserver_network}
          secgroup_ids: [{get_resource: security_group}]
          public_network: {get_param: webserver_public_network}
  scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: autoscaling_group}
      scaling_adjustment: 1
      cooldown: 60
  scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: autoscaling_group}
      scaling_adjustment: -1
      cooldown: 60
outputs:
  scale_up_alarmurl:
    description: "Alarm URL for scale up"
    value: {get_attr: [scaleup_policy, alarm_url]}
  scale_down_alarmurl:
    description: "Alarm URL for scale down"
    value: {get_attr: [scaledown_policy, alarm_url]}
  scale_up_webhook:
    description: "Webhook to trigger scale up"
    value: {get_attr: [scaleup_policy, signal_url]}
  scale_down_webhook:
    description: "Webhook to trigger scale down"
    value: {get_attr: [scaledown_policy, signal_url]}
