heat_template_version: 2018-08-31

description: |
  The heat template is used to create a simple server with floating ip.
parameters:
  name:
    type: string
  keypair:
    type: string
  image_id:
    type: string
  flavor_id:
    type: string
  network_id:
    type: string
    default: NETWORK-ID # Note(dalees): Requires a default for validation
  sg_ids:
    type: comma_delimited_list
  public_network:
    type: string

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: flavor_id }
      networks:
        - network: {get_param: network_id}
      key_name: {get_param: keypair}
      security_groups: {get_param: sg_ids}
      config_drive: true
      user_data_format: RAW
      user_data: { get_file: user_data.sh }
  server_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: public_network}
      port_id: {get_attr: [server, addresses, {get_param: network_id}, 0, port]}

outputs:
  server_id:
    value: {get_resource: server}
